# Generated by Django 6.0.1 on 2026-03-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("babycareapp", "0002_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="phone",
            new_name="phone_number",
        ),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("parent", "Parent"),
                    ("provider", "Childcare Provider"),
                    ("admin", "Admin"),
                ],
                default="parent",
                max_length=10,
            ),
        ),
    ]
