# Generated by Django 6.0.1 on 2026-03-18 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("babycareapp", "0004_service_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="register",
            name="role",
            field=models.CharField(default="parent", max_length=20),
        ),
    ]
