# Generated by Django 6.0.1 on 2026-03-18 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("babycareapp", "0005_register_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="babycareapp.register"
            ),
        ),
    ]
