# Generated by Django 6.0.1 on 2026-03-18 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("babycareapp", "0008_alter_service_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="service_images/"),
        ),
        migrations.AlterField(
            model_name="service",
            name="provider",
            field=models.ForeignKey(
                limit_choices_to={"role": "provider"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
