# Generated by Django 6.0.1 on 2026-03-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("babycareapp", "0009_service_image_alter_service_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
