# Generated by Django 6.0.1 on 2026-03-19 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("babycareapp", "0010_alter_service_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("reason", models.CharField(blank=True, max_length=100)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unavailability",
                        to="babycareapp.service",
                    ),
                ),
            ],
            options={
                "unique_together": {("service", "date")},
            },
        ),
    ]
