# Generated by Django 6.0.1 on 2026-04-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("babycareapp", "0012_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_typing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="last_activity",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="typing_to",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
