# Generated by Django 6.0.1 on 2026-04-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("babycareapp", "0014_alter_loginhistory_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
